version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: photo_app_db
    environment:
      MYSQL_ROOT_PASSWORD: d6jWcPGB#y@UFg43zRs95T
      MYSQL_DATABASE: photo_app
      MYSQL_USER: photo_app
      MYSQL_PASSWORD: bLKe#3dJt@zW7yP4RNTsx6
    ports:
      - "3306:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/data:/var/lib/mysql
    networks:
      - symfony

  photo_app:
    build:
      context: ./docker/apache
    container_name: photo_app_symfony
    depends_on:
      - db
    volumes:
      - .:/var/www/html/photo_app/
      
    ports:
      - 2520:8050
    restart: always
    entrypoint: sh /var/www/html/photo_app/docker/apache/start_server.sh
    networks:
      - symfony

  phpmyadmin:
    depends_on:
      - db
    container_name: photo_app_phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
      - db
    restart: always
    ports:
      - 8089:80
    environment:
      PMA_HOST: photo_app_db
      MYSQL_ROOT_PASSWORD: d6jWcPGB#y@UFg43zRs95T
    networks:
      - symfony

networks:
  symfony: